// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: collection.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection int32

const (
	Collection_UNKNOWN        Collection = 0
	Collection_USER           Collection = 1
	Collection_INCIDENT       Collection = 2
	Collection_INCIDENT_EVENT Collection = 3
)

// Enum value maps for Collection.
var (
	Collection_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER",
		2: "INCIDENT",
		3: "INCIDENT_EVENT",
	}
	Collection_value = map[string]int32{
		"UNKNOWN":        0,
		"USER":           1,
		"INCIDENT":       2,
		"INCIDENT_EVENT": 3,
	}
)

func (x Collection) Enum() *Collection {
	p := new(Collection)
	*p = x
	return p
}

func (x Collection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Collection) Descriptor() protoreflect.EnumDescriptor {
	return file_collection_proto_enumTypes[0].Descriptor()
}

func (Collection) Type() protoreflect.EnumType {
	return &file_collection_proto_enumTypes[0]
}

func (x Collection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Collection.Descriptor instead.
func (Collection) EnumDescriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{0}
}

var File_collection_proto protoreflect.FileDescriptor

const file_collection_proto_rawDesc = "" +
	"\n" +
	"\x10collection.proto*E\n" +
	"\n" +
	"Collection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\f\n" +
	"\bINCIDENT\x10\x02\x12\x12\n" +
	"\x0eINCIDENT_EVENT\x10\x03B\x11Z\x0f../emradiprotosb\x06proto3"

var (
	file_collection_proto_rawDescOnce sync.Once
	file_collection_proto_rawDescData []byte
)

func file_collection_proto_rawDescGZIP() []byte {
	file_collection_proto_rawDescOnce.Do(func() {
		file_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collection_proto_rawDesc), len(file_collection_proto_rawDesc)))
	})
	return file_collection_proto_rawDescData
}

var file_collection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_collection_proto_goTypes = []any{
	(Collection)(0), // 0: Collection
}
var file_collection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collection_proto_init() }
func file_collection_proto_init() {
	if File_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collection_proto_rawDesc), len(file_collection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collection_proto_goTypes,
		DependencyIndexes: file_collection_proto_depIdxs,
		EnumInfos:         file_collection_proto_enumTypes,
	}.Build()
	File_collection_proto = out.File
	file_collection_proto_goTypes = nil
	file_collection_proto_depIdxs = nil
}
