// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: incidentevent.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIncidentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Created       string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	AffectedUser  string                 `protobuf:"bytes,5,opt,name=affectedUser,proto3" json:"affectedUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncidentEvent) Reset() {
	*x = CreateIncidentEvent{}
	mi := &file_incidentevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncidentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentEvent) ProtoMessage() {}

func (x *CreateIncidentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_incidentevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentEvent.ProtoReflect.Descriptor instead.
func (*CreateIncidentEvent) Descriptor() ([]byte, []int) {
	return file_incidentevent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIncidentEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIncidentEvent) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CreateIncidentEvent) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateIncidentEvent) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateIncidentEvent) GetAffectedUser() string {
	if x != nil {
		return x.AffectedUser
	}
	return ""
}

type UpdateIncidentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Created       *string                `protobuf:"bytes,3,opt,name=created,proto3,oneof" json:"created,omitempty"`
	Notes         *string                `protobuf:"bytes,4,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,5,opt,name=createdBy,proto3,oneof" json:"createdBy,omitempty"`
	AffectedUser  *string                `protobuf:"bytes,6,opt,name=affectedUser,proto3,oneof" json:"affectedUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentEvent) Reset() {
	*x = UpdateIncidentEvent{}
	mi := &file_incidentevent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentEvent) ProtoMessage() {}

func (x *UpdateIncidentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_incidentevent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentEvent.ProtoReflect.Descriptor instead.
func (*UpdateIncidentEvent) Descriptor() ([]byte, []int) {
	return file_incidentevent_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateIncidentEvent) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpdateIncidentEvent) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateIncidentEvent) GetCreated() string {
	if x != nil && x.Created != nil {
		return *x.Created
	}
	return ""
}

func (x *UpdateIncidentEvent) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *UpdateIncidentEvent) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *UpdateIncidentEvent) GetAffectedUser() string {
	if x != nil && x.AffectedUser != nil {
		return *x.AffectedUser
	}
	return ""
}

var File_incidentevent_proto protoreflect.FileDescriptor

const file_incidentevent_proto_rawDesc = "" +
	"\n" +
	"\x13incidentevent.proto\"\xa9\x01\n" +
	"\x13CreateIncidentEvent\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x1c\n" +
	"\tcreatedBy\x18\x04 \x01(\tR\tcreatedBy\x12\"\n" +
	"\faffectedUser\x18\x05 \x01(\tR\faffectedUser\"\xa3\x02\n" +
	"\x13UpdateIncidentEvent\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\acreated\x18\x03 \x01(\tH\x02R\acreated\x88\x01\x01\x12\x19\n" +
	"\x05notes\x18\x04 \x01(\tH\x03R\x05notes\x88\x01\x01\x12!\n" +
	"\tcreatedBy\x18\x05 \x01(\tH\x04R\tcreatedBy\x88\x01\x01\x12'\n" +
	"\faffectedUser\x18\x06 \x01(\tH\x05R\faffectedUser\x88\x01\x01B\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_createdB\b\n" +
	"\x06_notesB\f\n" +
	"\n" +
	"_createdByB\x0f\n" +
	"\r_affectedUserB\x11Z\x0f../emradiprotosb\x06proto3"

var (
	file_incidentevent_proto_rawDescOnce sync.Once
	file_incidentevent_proto_rawDescData []byte
)

func file_incidentevent_proto_rawDescGZIP() []byte {
	file_incidentevent_proto_rawDescOnce.Do(func() {
		file_incidentevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incidentevent_proto_rawDesc), len(file_incidentevent_proto_rawDesc)))
	})
	return file_incidentevent_proto_rawDescData
}

var file_incidentevent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_incidentevent_proto_goTypes = []any{
	(*CreateIncidentEvent)(nil), // 0: CreateIncidentEvent
	(*UpdateIncidentEvent)(nil), // 1: UpdateIncidentEvent
}
var file_incidentevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_incidentevent_proto_init() }
func file_incidentevent_proto_init() {
	if File_incidentevent_proto != nil {
		return
	}
	file_incidentevent_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incidentevent_proto_rawDesc), len(file_incidentevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_incidentevent_proto_goTypes,
		DependencyIndexes: file_incidentevent_proto_depIdxs,
		MessageInfos:      file_incidentevent_proto_msgTypes,
	}.Build()
	File_incidentevent_proto = out.File
	file_incidentevent_proto_goTypes = nil
	file_incidentevent_proto_depIdxs = nil
}
