// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: incidentevent.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIncidentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Details       *string                `protobuf:"bytes,3,opt,name=details,proto3,oneof" json:"details,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	AffectedUsers []uint32               `protobuf:"varint,5,rep,packed,name=affectedUsers,proto3" json:"affectedUsers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncidentEvent) Reset() {
	*x = CreateIncidentEvent{}
	mi := &file_incidentevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncidentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentEvent) ProtoMessage() {}

func (x *CreateIncidentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_incidentevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentEvent.ProtoReflect.Descriptor instead.
func (*CreateIncidentEvent) Descriptor() ([]byte, []int) {
	return file_incidentevent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIncidentEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateIncidentEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIncidentEvent) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *CreateIncidentEvent) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateIncidentEvent) GetAffectedUsers() []uint32 {
	if x != nil {
		return x.AffectedUsers
	}
	return nil
}

type UpdateIncidentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Details       *string                `protobuf:"bytes,3,opt,name=details,proto3,oneof" json:"details,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	AffectedUsers []uint32               `protobuf:"varint,5,rep,packed,name=affectedUsers,proto3" json:"affectedUsers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentEvent) Reset() {
	*x = UpdateIncidentEvent{}
	mi := &file_incidentevent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentEvent) ProtoMessage() {}

func (x *UpdateIncidentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_incidentevent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentEvent.ProtoReflect.Descriptor instead.
func (*UpdateIncidentEvent) Descriptor() ([]byte, []int) {
	return file_incidentevent_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateIncidentEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateIncidentEvent) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateIncidentEvent) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *UpdateIncidentEvent) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *UpdateIncidentEvent) GetAffectedUsers() []uint32 {
	if x != nil {
		return x.AffectedUsers
	}
	return nil
}

var File_incidentevent_proto protoreflect.FileDescriptor

const file_incidentevent_proto_rawDesc = "" +
	"\n" +
	"\x13incidentevent.proto\"\xaa\x01\n" +
	"\x13CreateIncidentEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\adetails\x18\x03 \x01(\tH\x00R\adetails\x88\x01\x01\x12\x1c\n" +
	"\tcreatedBy\x18\x04 \x01(\tR\tcreatedBy\x12$\n" +
	"\raffectedUsers\x18\x05 \x03(\rR\raffectedUsersB\n" +
	"\n" +
	"\b_details\"\xb9\x01\n" +
	"\x13UpdateIncidentEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\adetails\x18\x03 \x01(\tH\x01R\adetails\x88\x01\x01\x12\x1c\n" +
	"\tcreatedBy\x18\x04 \x01(\tR\tcreatedBy\x12$\n" +
	"\raffectedUsers\x18\x05 \x03(\rR\raffectedUsersB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_detailsB\x11Z\x0f../emradiprotosb\x06proto3"

var (
	file_incidentevent_proto_rawDescOnce sync.Once
	file_incidentevent_proto_rawDescData []byte
)

func file_incidentevent_proto_rawDescGZIP() []byte {
	file_incidentevent_proto_rawDescOnce.Do(func() {
		file_incidentevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incidentevent_proto_rawDesc), len(file_incidentevent_proto_rawDesc)))
	})
	return file_incidentevent_proto_rawDescData
}

var file_incidentevent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_incidentevent_proto_goTypes = []any{
	(*CreateIncidentEvent)(nil), // 0: CreateIncidentEvent
	(*UpdateIncidentEvent)(nil), // 1: UpdateIncidentEvent
}
var file_incidentevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_incidentevent_proto_init() }
func file_incidentevent_proto_init() {
	if File_incidentevent_proto != nil {
		return
	}
	file_incidentevent_proto_msgTypes[0].OneofWrappers = []any{}
	file_incidentevent_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incidentevent_proto_rawDesc), len(file_incidentevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_incidentevent_proto_goTypes,
		DependencyIndexes: file_incidentevent_proto_depIdxs,
		MessageInfos:      file_incidentevent_proto_msgTypes,
	}.Build()
	File_incidentevent_proto = out.File
	file_incidentevent_proto_goTypes = nil
	file_incidentevent_proto_depIdxs = nil
}
