// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: incident.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIncident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	IncidentType  string                 `protobuf:"bytes,3,opt,name=incidentType,proto3" json:"incidentType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncident) Reset() {
	*x = CreateIncident{}
	mi := &file_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncident) ProtoMessage() {}

func (x *CreateIncident) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncident.ProtoReflect.Descriptor instead.
func (*CreateIncident) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIncident) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateIncident) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateIncident) GetIncidentType() string {
	if x != nil {
		return x.IncidentType
	}
	return ""
}

type UpdateIncident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude      *float32               `protobuf:"fixed32,2,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float32               `protobuf:"fixed32,3,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	IncidentType  *string                `protobuf:"bytes,4,opt,name=incidentType,proto3,oneof" json:"incidentType,omitempty"`
	ClosedAt      *string                `protobuf:"bytes,5,opt,name=closedAt,proto3,oneof" json:"closedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncident) Reset() {
	*x = UpdateIncident{}
	mi := &file_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncident) ProtoMessage() {}

func (x *UpdateIncident) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncident.ProtoReflect.Descriptor instead.
func (*UpdateIncident) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateIncident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIncident) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdateIncident) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *UpdateIncident) GetIncidentType() string {
	if x != nil && x.IncidentType != nil {
		return *x.IncidentType
	}
	return ""
}

func (x *UpdateIncident) GetClosedAt() string {
	if x != nil && x.ClosedAt != nil {
		return *x.ClosedAt
	}
	return ""
}

var File_incident_proto protoreflect.FileDescriptor

const file_incident_proto_rawDesc = "" +
	"\n" +
	"\x0eincident.proto\"n\n" +
	"\x0eCreateIncident\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x12\"\n" +
	"\fincidentType\x18\x03 \x01(\tR\fincidentType\"\xe7\x01\n" +
	"\x0eUpdateIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\blatitude\x18\x02 \x01(\x02H\x00R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x03 \x01(\x02H\x01R\tlongitude\x88\x01\x01\x12'\n" +
	"\fincidentType\x18\x04 \x01(\tH\x02R\fincidentType\x88\x01\x01\x12\x1f\n" +
	"\bclosedAt\x18\x05 \x01(\tH\x03R\bclosedAt\x88\x01\x01B\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\x0f\n" +
	"\r_incidentTypeB\v\n" +
	"\t_closedAtB\x11Z\x0f../emradiprotosb\x06proto3"

var (
	file_incident_proto_rawDescOnce sync.Once
	file_incident_proto_rawDescData []byte
)

func file_incident_proto_rawDescGZIP() []byte {
	file_incident_proto_rawDescOnce.Do(func() {
		file_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)))
	})
	return file_incident_proto_rawDescData
}

var file_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_incident_proto_goTypes = []any{
	(*CreateIncident)(nil), // 0: CreateIncident
	(*UpdateIncident)(nil), // 1: UpdateIncident
}
var file_incident_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_incident_proto_init() }
func file_incident_proto_init() {
	if File_incident_proto != nil {
		return
	}
	file_incident_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_incident_proto_goTypes,
		DependencyIndexes: file_incident_proto_depIdxs,
		MessageInfos:      file_incident_proto_msgTypes,
	}.Build()
	File_incident_proto = out.File
	file_incident_proto_goTypes = nil
	file_incident_proto_depIdxs = nil
}
