// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: main.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid for the request
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_CreateUser
	//	*Request_CreateIncident
	//	*Request_CreateIncidentEvent
	//	*Request_Read
	//	*Request_UpdateUser
	//	*Request_UpdateIncident
	//	*Request_UpdateIncidentEvent
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetCreateUser() *CreateUser {
	if x != nil {
		if x, ok := x.Payload.(*Request_CreateUser); ok {
			return x.CreateUser
		}
	}
	return nil
}

func (x *Request) GetCreateIncident() *CreateIncident {
	if x != nil {
		if x, ok := x.Payload.(*Request_CreateIncident); ok {
			return x.CreateIncident
		}
	}
	return nil
}

func (x *Request) GetCreateIncidentEvent() *CreateIncidentEvent {
	if x != nil {
		if x, ok := x.Payload.(*Request_CreateIncidentEvent); ok {
			return x.CreateIncidentEvent
		}
	}
	return nil
}

func (x *Request) GetRead() *Read {
	if x != nil {
		if x, ok := x.Payload.(*Request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) GetUpdateUser() *UpdateUser {
	if x != nil {
		if x, ok := x.Payload.(*Request_UpdateUser); ok {
			return x.UpdateUser
		}
	}
	return nil
}

func (x *Request) GetUpdateIncident() *UpdateIncident {
	if x != nil {
		if x, ok := x.Payload.(*Request_UpdateIncident); ok {
			return x.UpdateIncident
		}
	}
	return nil
}

func (x *Request) GetUpdateIncidentEvent() *UpdateIncidentEvent {
	if x != nil {
		if x, ok := x.Payload.(*Request_UpdateIncidentEvent); ok {
			return x.UpdateIncidentEvent
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_CreateUser struct {
	CreateUser *CreateUser `protobuf:"bytes,2,opt,name=createUser,proto3,oneof"`
}

type Request_CreateIncident struct {
	CreateIncident *CreateIncident `protobuf:"bytes,3,opt,name=createIncident,proto3,oneof"`
}

type Request_CreateIncidentEvent struct {
	CreateIncidentEvent *CreateIncidentEvent `protobuf:"bytes,4,opt,name=createIncidentEvent,proto3,oneof"`
}

type Request_Read struct {
	Read *Read `protobuf:"bytes,5,opt,name=read,proto3,oneof"`
}

type Request_UpdateUser struct {
	UpdateUser *UpdateUser `protobuf:"bytes,6,opt,name=updateUser,proto3,oneof"`
}

type Request_UpdateIncident struct {
	UpdateIncident *UpdateIncident `protobuf:"bytes,7,opt,name=updateIncident,proto3,oneof"`
}

type Request_UpdateIncidentEvent struct {
	UpdateIncidentEvent *UpdateIncidentEvent `protobuf:"bytes,8,opt,name=updateIncidentEvent,proto3,oneof"` // no delete yet, but we can add it later if needed
}

func (*Request_CreateUser) isRequest_Payload() {}

func (*Request_CreateIncident) isRequest_Payload() {}

func (*Request_CreateIncidentEvent) isRequest_Payload() {}

func (*Request_Read) isRequest_Payload() {}

func (*Request_UpdateUser) isRequest_Payload() {}

func (*Request_UpdateIncident) isRequest_Payload() {}

func (*Request_UpdateIncidentEvent) isRequest_Payload() {}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                 // uuid for the response, corresponding to the request id
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`        // e.g. HTTP status code
	Payload       *string                `protobuf:"bytes,3,opt,name=payload,proto3,oneof" json:"payload,omitempty"` // id for create, JSON for read, nil for update, or detailed error message on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

type EmradiMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EmradiMessage_Request
	//	*EmradiMessage_Response
	Payload       isEmradiMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmradiMessage) Reset() {
	*x = EmradiMessage{}
	mi := &file_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmradiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmradiMessage) ProtoMessage() {}

func (x *EmradiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmradiMessage.ProtoReflect.Descriptor instead.
func (*EmradiMessage) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{2}
}

func (x *EmradiMessage) GetPayload() isEmradiMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EmradiMessage) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Payload.(*EmradiMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *EmradiMessage) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Payload.(*EmradiMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isEmradiMessage_Payload interface {
	isEmradiMessage_Payload()
}

type EmradiMessage_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type EmradiMessage_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*EmradiMessage_Request) isEmradiMessage_Payload() {}

func (*EmradiMessage_Response) isEmradiMessage_Payload() {}

var File_main_proto protoreflect.FileDescriptor

const file_main_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"main.proto\x1a\n" +
	"user.proto\x1a\x0eincident.proto\x1a\x13incidentevent.proto\x1a\n" +
	"read.proto\"\xa9\x03\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\n" +
	"createUser\x18\x02 \x01(\v2\v.CreateUserH\x00R\n" +
	"createUser\x129\n" +
	"\x0ecreateIncident\x18\x03 \x01(\v2\x0f.CreateIncidentH\x00R\x0ecreateIncident\x12H\n" +
	"\x13createIncidentEvent\x18\x04 \x01(\v2\x14.CreateIncidentEventH\x00R\x13createIncidentEvent\x12\x1b\n" +
	"\x04read\x18\x05 \x01(\v2\x05.ReadH\x00R\x04read\x12-\n" +
	"\n" +
	"updateUser\x18\x06 \x01(\v2\v.UpdateUserH\x00R\n" +
	"updateUser\x129\n" +
	"\x0eupdateIncident\x18\a \x01(\v2\x0f.UpdateIncidentH\x00R\x0eupdateIncident\x12H\n" +
	"\x13updateIncidentEvent\x18\b \x01(\v2\x14.UpdateIncidentEventH\x00R\x13updateIncidentEventB\t\n" +
	"\apayload\"]\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1d\n" +
	"\apayload\x18\x03 \x01(\tH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload\"i\n" +
	"\rEmradiMessage\x12$\n" +
	"\arequest\x18\x01 \x01(\v2\b.RequestH\x00R\arequest\x12'\n" +
	"\bresponse\x18\x02 \x01(\v2\t.ResponseH\x00R\bresponseB\t\n" +
	"\apayloadB\x11Z\x0f../emradiprotosb\x06proto3"

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData []byte
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)))
	})
	return file_main_proto_rawDescData
}

var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_main_proto_goTypes = []any{
	(*Request)(nil),             // 0: Request
	(*Response)(nil),            // 1: Response
	(*EmradiMessage)(nil),       // 2: EmradiMessage
	(*CreateUser)(nil),          // 3: CreateUser
	(*CreateIncident)(nil),      // 4: CreateIncident
	(*CreateIncidentEvent)(nil), // 5: CreateIncidentEvent
	(*Read)(nil),                // 6: Read
	(*UpdateUser)(nil),          // 7: UpdateUser
	(*UpdateIncident)(nil),      // 8: UpdateIncident
	(*UpdateIncidentEvent)(nil), // 9: UpdateIncidentEvent
}
var file_main_proto_depIdxs = []int32{
	3, // 0: Request.createUser:type_name -> CreateUser
	4, // 1: Request.createIncident:type_name -> CreateIncident
	5, // 2: Request.createIncidentEvent:type_name -> CreateIncidentEvent
	6, // 3: Request.read:type_name -> Read
	7, // 4: Request.updateUser:type_name -> UpdateUser
	8, // 5: Request.updateIncident:type_name -> UpdateIncident
	9, // 6: Request.updateIncidentEvent:type_name -> UpdateIncidentEvent
	0, // 7: EmradiMessage.request:type_name -> Request
	1, // 8: EmradiMessage.response:type_name -> Response
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	file_user_proto_init()
	file_incident_proto_init()
	file_incidentevent_proto_init()
	file_read_proto_init()
	file_main_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_CreateUser)(nil),
		(*Request_CreateIncident)(nil),
		(*Request_CreateIncidentEvent)(nil),
		(*Request_Read)(nil),
		(*Request_UpdateUser)(nil),
		(*Request_UpdateIncident)(nil),
		(*Request_UpdateIncidentEvent)(nil),
	}
	file_main_proto_msgTypes[1].OneofWrappers = []any{}
	file_main_proto_msgTypes[2].OneofWrappers = []any{
		(*EmradiMessage_Request)(nil),
		(*EmradiMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
