// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: read.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Read struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiple      bool                   `protobuf:"varint,1,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Collection    Collection             `protobuf:"varint,2,opt,name=collection,proto3,enum=Collection" json:"collection,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort          *string                `protobuf:"bytes,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Limit         *uint32                `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint32                `protobuf:"varint,6,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{0}
}

func (x *Read) GetMultiple() bool {
	if x != nil {
		return x.Multiple
	}
	return false
}

func (x *Read) GetCollection() Collection {
	if x != nil {
		return x.Collection
	}
	return Collection_UNKNOWN
}

func (x *Read) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *Read) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *Read) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *Read) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

var File_read_proto protoreflect.FileDescriptor

const file_read_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"read.proto\x1a\x10collection.proto\"\xd6\x01\n" +
	"\x04Read\x12\x1a\n" +
	"\bmultiple\x18\x01 \x01(\bR\bmultiple\x12+\n" +
	"\n" +
	"collection\x18\x02 \x01(\x0e2\v.CollectionR\n" +
	"collection\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\tH\x00R\x04sort\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\rH\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x06 \x01(\rH\x02R\x06offset\x88\x01\x01B\a\n" +
	"\x05_sortB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x11Z\x0f../emradiprotosb\x06proto3"

var (
	file_read_proto_rawDescOnce sync.Once
	file_read_proto_rawDescData []byte
)

func file_read_proto_rawDescGZIP() []byte {
	file_read_proto_rawDescOnce.Do(func() {
		file_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_read_proto_rawDesc), len(file_read_proto_rawDesc)))
	})
	return file_read_proto_rawDescData
}

var file_read_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_read_proto_goTypes = []any{
	(*Read)(nil),    // 0: Read
	(Collection)(0), // 1: Collection
}
var file_read_proto_depIdxs = []int32{
	1, // 0: Read.collection:type_name -> Collection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_read_proto_init() }
func file_read_proto_init() {
	if File_read_proto != nil {
		return
	}
	file_collection_proto_init()
	file_read_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_read_proto_rawDesc), len(file_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_read_proto_goTypes,
		DependencyIndexes: file_read_proto_depIdxs,
		MessageInfos:      file_read_proto_msgTypes,
	}.Build()
	File_read_proto = out.File
	file_read_proto_goTypes = nil
	file_read_proto_depIdxs = nil
}
