// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: main.proto

package meshcadprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshcadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Numerator     uint32                 `protobuf:"varint,2,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator   uint32                 `protobuf:"varint,3,opt,name=denominator,proto3" json:"denominator,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshcadChunk) Reset() {
	*x = MeshcadChunk{}
	mi := &file_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshcadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshcadChunk) ProtoMessage() {}

func (x *MeshcadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshcadChunk.ProtoReflect.Descriptor instead.
func (*MeshcadChunk) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

func (x *MeshcadChunk) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MeshcadChunk) GetNumerator() uint32 {
	if x != nil {
		return x.Numerator
	}
	return 0
}

func (x *MeshcadChunk) GetDenominator() uint32 {
	if x != nil {
		return x.Denominator
	}
	return 0
}

func (x *MeshcadChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`        // HTTP status code
	Payload       *string                `protobuf:"bytes,2,opt,name=payload,proto3,oneof" json:"payload,omitempty"` // id for create or authorize, JSON for read, nil for update, or detailed error message on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

type Payload struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp uint32                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Payload_Response
	//	*Payload_CreateUser
	//	*Payload_CreateIncident
	//	*Payload_CreateIncidentEvent
	//	*Payload_Read
	//	*Payload_UpdateUser
	//	*Payload_UpdateIncident
	//	*Payload_UpdateIncidentEvent
	//	*Payload_AuthorizeUser
	Payload       isPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{2}
}

func (x *Payload) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Payload) GetPayload() isPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Payload) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Payload.(*Payload_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Payload) GetCreateUser() *CreateUser {
	if x != nil {
		if x, ok := x.Payload.(*Payload_CreateUser); ok {
			return x.CreateUser
		}
	}
	return nil
}

func (x *Payload) GetCreateIncident() *CreateIncident {
	if x != nil {
		if x, ok := x.Payload.(*Payload_CreateIncident); ok {
			return x.CreateIncident
		}
	}
	return nil
}

func (x *Payload) GetCreateIncidentEvent() *CreateIncidentEvent {
	if x != nil {
		if x, ok := x.Payload.(*Payload_CreateIncidentEvent); ok {
			return x.CreateIncidentEvent
		}
	}
	return nil
}

func (x *Payload) GetRead() *Read {
	if x != nil {
		if x, ok := x.Payload.(*Payload_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Payload) GetUpdateUser() *UpdateUser {
	if x != nil {
		if x, ok := x.Payload.(*Payload_UpdateUser); ok {
			return x.UpdateUser
		}
	}
	return nil
}

func (x *Payload) GetUpdateIncident() *UpdateIncident {
	if x != nil {
		if x, ok := x.Payload.(*Payload_UpdateIncident); ok {
			return x.UpdateIncident
		}
	}
	return nil
}

func (x *Payload) GetUpdateIncidentEvent() *UpdateIncidentEvent {
	if x != nil {
		if x, ok := x.Payload.(*Payload_UpdateIncidentEvent); ok {
			return x.UpdateIncidentEvent
		}
	}
	return nil
}

func (x *Payload) GetAuthorizeUser() *AuthorizeUser {
	if x != nil {
		if x, ok := x.Payload.(*Payload_AuthorizeUser); ok {
			return x.AuthorizeUser
		}
	}
	return nil
}

type isPayload_Payload interface {
	isPayload_Payload()
}

type Payload_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type Payload_CreateUser struct {
	CreateUser *CreateUser `protobuf:"bytes,3,opt,name=createUser,proto3,oneof"`
}

type Payload_CreateIncident struct {
	CreateIncident *CreateIncident `protobuf:"bytes,4,opt,name=createIncident,proto3,oneof"`
}

type Payload_CreateIncidentEvent struct {
	CreateIncidentEvent *CreateIncidentEvent `protobuf:"bytes,5,opt,name=createIncidentEvent,proto3,oneof"`
}

type Payload_Read struct {
	Read *Read `protobuf:"bytes,6,opt,name=read,proto3,oneof"`
}

type Payload_UpdateUser struct {
	UpdateUser *UpdateUser `protobuf:"bytes,7,opt,name=updateUser,proto3,oneof"`
}

type Payload_UpdateIncident struct {
	UpdateIncident *UpdateIncident `protobuf:"bytes,8,opt,name=updateIncident,proto3,oneof"`
}

type Payload_UpdateIncidentEvent struct {
	UpdateIncidentEvent *UpdateIncidentEvent `protobuf:"bytes,9,opt,name=updateIncidentEvent,proto3,oneof"`
}

type Payload_AuthorizeUser struct {
	AuthorizeUser *AuthorizeUser `protobuf:"bytes,10,opt,name=authorizeUser,proto3,oneof"` // no delete yet, but we can add it later if needed
}

func (*Payload_Response) isPayload_Payload() {}

func (*Payload_CreateUser) isPayload_Payload() {}

func (*Payload_CreateIncident) isPayload_Payload() {}

func (*Payload_CreateIncidentEvent) isPayload_Payload() {}

func (*Payload_Read) isPayload_Payload() {}

func (*Payload_UpdateUser) isPayload_Payload() {}

func (*Payload_UpdateIncident) isPayload_Payload() {}

func (*Payload_UpdateIncidentEvent) isPayload_Payload() {}

func (*Payload_AuthorizeUser) isPayload_Payload() {}

var File_main_proto protoreflect.FileDescriptor

const file_main_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"main.proto\x1a\n" +
	"user.proto\x1a\x0eincident.proto\x1a\x13incidentevent.proto\x1a\n" +
	"read.proto\"x\n" +
	"\fMeshcadChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1c\n" +
	"\tnumerator\x18\x02 \x01(\rR\tnumerator\x12 \n" +
	"\vdenominator\x18\x03 \x01(\rR\vdenominator\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"M\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x1d\n" +
	"\apayload\x18\x02 \x01(\tH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload\"\x98\x04\n" +
	"\aPayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\rR\ttimestamp\x12'\n" +
	"\bresponse\x18\x02 \x01(\v2\t.ResponseH\x00R\bresponse\x12-\n" +
	"\n" +
	"createUser\x18\x03 \x01(\v2\v.CreateUserH\x00R\n" +
	"createUser\x129\n" +
	"\x0ecreateIncident\x18\x04 \x01(\v2\x0f.CreateIncidentH\x00R\x0ecreateIncident\x12H\n" +
	"\x13createIncidentEvent\x18\x05 \x01(\v2\x14.CreateIncidentEventH\x00R\x13createIncidentEvent\x12\x1b\n" +
	"\x04read\x18\x06 \x01(\v2\x05.ReadH\x00R\x04read\x12-\n" +
	"\n" +
	"updateUser\x18\a \x01(\v2\v.UpdateUserH\x00R\n" +
	"updateUser\x129\n" +
	"\x0eupdateIncident\x18\b \x01(\v2\x0f.UpdateIncidentH\x00R\x0eupdateIncident\x12H\n" +
	"\x13updateIncidentEvent\x18\t \x01(\v2\x14.UpdateIncidentEventH\x00R\x13updateIncidentEvent\x126\n" +
	"\rauthorizeUser\x18\n" +
	" \x01(\v2\x0e.AuthorizeUserH\x00R\rauthorizeUserB\t\n" +
	"\apayloadB\x12Z\x10../meshcadprotosb\x06proto3"

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData []byte
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)))
	})
	return file_main_proto_rawDescData
}

var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_main_proto_goTypes = []any{
	(*MeshcadChunk)(nil),        // 0: MeshcadChunk
	(*Response)(nil),            // 1: Response
	(*Payload)(nil),             // 2: Payload
	(*CreateUser)(nil),          // 3: CreateUser
	(*CreateIncident)(nil),      // 4: CreateIncident
	(*CreateIncidentEvent)(nil), // 5: CreateIncidentEvent
	(*Read)(nil),                // 6: Read
	(*UpdateUser)(nil),          // 7: UpdateUser
	(*UpdateIncident)(nil),      // 8: UpdateIncident
	(*UpdateIncidentEvent)(nil), // 9: UpdateIncidentEvent
	(*AuthorizeUser)(nil),       // 10: AuthorizeUser
}
var file_main_proto_depIdxs = []int32{
	1,  // 0: Payload.response:type_name -> Response
	3,  // 1: Payload.createUser:type_name -> CreateUser
	4,  // 2: Payload.createIncident:type_name -> CreateIncident
	5,  // 3: Payload.createIncidentEvent:type_name -> CreateIncidentEvent
	6,  // 4: Payload.read:type_name -> Read
	7,  // 5: Payload.updateUser:type_name -> UpdateUser
	8,  // 6: Payload.updateIncident:type_name -> UpdateIncident
	9,  // 7: Payload.updateIncidentEvent:type_name -> UpdateIncidentEvent
	10, // 8: Payload.authorizeUser:type_name -> AuthorizeUser
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	file_user_proto_init()
	file_incident_proto_init()
	file_incidentevent_proto_init()
	file_read_proto_init()
	file_main_proto_msgTypes[1].OneofWrappers = []any{}
	file_main_proto_msgTypes[2].OneofWrappers = []any{
		(*Payload_Response)(nil),
		(*Payload_CreateUser)(nil),
		(*Payload_CreateIncident)(nil),
		(*Payload_CreateIncidentEvent)(nil),
		(*Payload_Read)(nil),
		(*Payload_UpdateUser)(nil),
		(*Payload_UpdateIncident)(nil),
		(*Payload_UpdateIncidentEvent)(nil),
		(*Payload_AuthorizeUser)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
